amocrm:
  integration_id: str
  secret_key: str
  auth_code: str
  base_url: str
  redirect_uri: str

rate_limiter:
  interval_length: 1
  max_request_count: 7
  forced_delay: 1

repeater:
  tries: 5
  delay: 1.0
  max_delay: 5.0
  backoff: 0
