integration_id: xxxxxxxx-xxxx-xxxx-xxx-xxxxxxxxxxxx
secret_key: secret_key
auth_code: auth_code
redirect_uri: https://mycompany.ru/
base_url: https://account.amocrm.ru/

rate_limiter:
  interval_length: 1
  max_request_count: 7
  forced_delay: 1

repeater:
  tries: 5
  delay: 1.0
  max_delay: 5.0
  backoff: 0

storage:
  type: redis
  settings:
    host: 127.0.0.1
    port: 6379
    database: 1
    prefix: amocrm-api-client
